### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by h0dger** [qbcore-framework/qb-ambulancejob#213] opened 2022-07-31 23:25 UTC
Config was fine now out of the blue the garage will show the vehicle list but will not spawn them. We can command spawn them but the garage will not do it as designed.

**Comment by GhzGarage** [comment] 2022-08-01 00:30
Did you update this script and not add the callbacks in the core ?

**Comment by h0dger** [comment] 2022-08-01 00:30
I have grabbed it and swapped all my info to the brand new version and ensured and still have the same issue

**Comment by h0dger** [comment] 2022-08-01 11:02
its spawning blocks away under the map now and i have tried adjusting the cords

**Comment by h0dger** [comment] 2022-08-01 19:25
[](url)
![image](https://user-images.githubusercontent.com/98565787/182229567-9331a987-1067-441c-9a24-3fe261b30780.png)
these are the active codes

**Comment by h0dger** [comment] 2022-08-01 21:47
got the codes cleared up but the vehicles still wont spawn now

**Comment by h0dger** [comment] 2022-08-02 20:21
[](url)
![image](https://user-images.githubusercontent.com/98565787/182466031-3b731ddb-5bf5-4e4b-85b1-a92d62876ed4.png)

anything visually wrong here?

**Comment by singh-manavv** [comment] 2022-09-02 15:32
> ![image](https://user-images.githubusercontent.com/98565787/182229567-9331a987-1067-441c-9a24-3fe261b30780.png) these are the active codes

It seems your config file doesn't seems to be running , which could be because of any commas left or brackets left open . Look into that

**Comment by i-kulgu** [comment] 2023-01-06 09:07
Fixed within the latest version, can't reproduce.

**Closed** 2023-01-08 12:54 UTC
Labels: bug
